descripcion: 'Goyo - Defender AR (TCSG12 + AK-74M)'
horizontal_range: 0.14
recoil_intensity: 0.7
min_vertical: 5
max_vertical: 7
min_firerate: 0.01
max_firerate: 0.015
bonus_offset: 'random.uniform(-0.2, 0.2)'
horizontal_offset: 'random.uniform(-0.35, 0.35)'
vertical_offset: 'random.uniform(5, 7)'
time_offset: 'random.uniform(0.01, 0.015)'
