descripcion: 'IQ - Attacker AR (HK416)'
horizontal_range: 0.08
recoil_intensity: 0.7
min_vertical: 4
max_vertical: 6
min_firerate: 0.008
max_firerate: 0.012
bonus_offset: 'random.uniform(-0.15, 0.15)'
horizontal_offset: 'random.uniform(-0.3, 0.3)'
vertical_offset: 'random.uniform(3, 6)'
time_offset: 'random.uniform(0.008, 0.012)'
